<?php

/**
 * @file
 * Implementation of robertson library morphospace customizations.
 */

/**
 * Implements hook_islandora_object_ingested
 */
function upei_roblib_morpho_exts_islandora_object_ingested($object) {
  if (empty($object['MODS'])) {
    return;
  }
  $datastream = $object['MODS'];
  // content models we are interested in customizing
  $cmodels = array(
    'islandora:sp_basic_image',
    'islandora:sp_large_image_cmodel',
  );
  if (count(array_intersect($object->models, $cmodels)) > 0) {
    upei_roblib_morpho_exts_add_parentinfo_to_mods($object, $datastream);
  }

}

/**
 * Add the parent object's label to a mods element.
 * @param $object
 *   The Islandora object
 * @param $datastream
 *   The Islandora datastream
 * @return bool
 */
function upei_roblib_morpho_exts_add_parentinfo_to_mods($object, $datastream) {
  $parents = $object->relationships->get(NULL, 'isMemberOfCollection');
  $parent = reset($parents);
  $parent_pid = $parent['object']['value'];
  $parent = islandora_object_load($parent_pid);
  //assuming only one parent here for now
  $mods_content = $datastream->content;
  if (empty($mods_content)) {
    watchdog('upei_roblib_morpho_exts', 'Could not add species info to MODS datastream datastream not found for object %pid',
      array('%pid' => $object->id), WATCHDOG_INFO);
    return FALSE;
  }
  if (empty($parent)) {
    watchdog('upei_roblib_morpho_exts', 'Could not add species info to MODS datastream parent object not found for object %pid',
      array('%pid' => $object->id), WATCHDOG_INFO);
    return FALSE;
  }
  $label = $parent->label;
  $mods_doc = @DOMDocument::loadXML($mods_content);
  $mods_xpath = new DOMXPath($mods_doc);
  $mods_xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
  $species_results = $mods_xpath->query('//mods:note[@type="species"]');
  if ($species_results->length > 0) {
    // take the first species
    $species = $species_results->item(0);
  }
  if (empty($species)) {
    $mods_element = $mods_doc->getElementsByTagName('mods');
    $species_note = $mods_doc->createElement("note", $label);
    $species_note->setAttribute('type', 'species');
    $mods_element->item(0)->appendChild($species_note);
  }
  else {
    $species->nodeValue = $label;
  }
  $mods_xml = $mods_doc->saveXML();
  $datastream->content = $mods_xml;
}

